catch { set_global_assignment -name DEVICE EPM7128SLC84-15 } result
catch { set_global_assignment -name RESERVED_ALL_UNUSED_PINS "AS INPUT TRI-STATED" } result
catch { set_location_assignment PIN_1 -to reset } result
catch { set_location_assignment PIN_2 -to clk } result
catch { set_location_assignment PIN_4 -to pVdata\[0\] } result
catch { set_location_assignment PIN_5 -to pVdata\[1\] } result
catch { set_location_assignment PIN_8 -to pVdata\[2\] } result
catch { set_location_assignment PIN_9 -to pVdata\[3\] } result
catch { set_location_assignment PIN_10 -to pVdata\[4\] } result
catch { set_location_assignment PIN_11 -to pVdata\[5\] } result
catch { set_location_assignment PIN_12 -to pVdata\[6\] } result
catch { set_location_assignment PIN_15 -to pVdata\[7\] } result
catch { set_location_assignment PIN_16 -to pVaddr\[0\] } result
catch { set_location_assignment PIN_17 -to pVaddr\[1\] } result
catch { set_location_assignment PIN_18 -to pVaddr\[2\] } result
catch { set_location_assignment PIN_20 -to pVaddr\[3\] } result
catch { set_location_assignment PIN_21 -to pVaddr\[4\] } result
catch { set_location_assignment PIN_22 -to pVaddr\[5\] } result
catch { set_location_assignment PIN_24 -to pVaddr\[6\] } result
catch { set_location_assignment PIN_25 -to pVaddr\[7\] } result
catch { set_location_assignment PIN_27 -to pVaddr\[8\] } result
catch { set_location_assignment PIN_28 -to pVaddr\[9\] } result
catch { set_location_assignment PIN_29 -to pVaddr\[10\] } result
catch { set_location_assignment PIN_30 -to pVaddr\[11\] } result
catch { set_location_assignment PIN_31 -to pVaddr\[12\] } result
catch { set_location_assignment PIN_33 -to pVaddr\[13\] } result
catch { set_location_assignment PIN_34 -to pVaddr\[14\] } result
catch { set_location_assignment PIN_35 -to pVenable } result
catch { set_location_assignment PIN_36 -to pVwrite } result
catch { set_location_assignment PIN_37 -to pR } result
catch { set_location_assignment PIN_40 -to pG } result
catch { set_location_assignment PIN_41 -to pB } result
catch { set_location_assignment PIN_44 -to pI } result
catch { set_location_assignment PIN_45 -to pHSYNC } result
catch { set_location_assignment PIN_48 -to pVSYNC } result
catch { set_location_assignment PIN_49 -to pAaddr\[0\] } result
catch { set_location_assignment PIN_50 -to pAaddr\[1\] } result
catch { set_location_assignment PIN_51 -to pAaddr\[2\] } result
catch { set_location_assignment PIN_52 -to pAaddr\[3\] } result
catch { set_location_assignment PIN_54 -to pAaddr\[4\] } result
catch { set_location_assignment PIN_55 -to pAaddr\[5\] } result
catch { set_location_assignment PIN_56 -to pAaddr\[6\] } result
catch { set_location_assignment PIN_57 -to pAaddr\[7\] } result
catch { set_location_assignment PIN_58 -to pAaddr\[8\] } result
catch { set_location_assignment PIN_60 -to pAaddr\[9\] } result
catch { set_location_assignment PIN_61 -to pAaddr\[10\] } result
catch { set_location_assignment PIN_63 -to pAaddr\[11\] } result
catch { set_location_assignment PIN_64 -to pAaddr\[12\] } result
catch { set_location_assignment PIN_65 -to pAaddr\[13\] } result
catch { set_location_assignment PIN_67 -to pAaddr\[14\] } result
catch { set_location_assignment PIN_68 -to pAaddr\[15\] } result
catch { set_location_assignment PIN_69 -to pAdata\[0\] } result
catch { set_location_assignment PIN_70 -to pAdata\[1\] } result
catch { set_location_assignment PIN_73 -to pAdata\[2\] } result
catch { set_location_assignment PIN_74 -to pAdata\[3\] } result
catch { set_location_assignment PIN_75 -to pAdata\[4\] } result
catch { set_location_assignment PIN_76 -to pAdata\[5\] } result
catch { set_location_assignment PIN_77 -to pAdata\[6\] } result
catch { set_location_assignment PIN_80 -to pAdata\[7\] } result
catch { set_location_assignment PIN_81 -to pArw } result
catch { set_location_assignment PIN_83 -to pAphi0 } result
catch { set_location_assignment PIN_84 -to pAq3 } result
